# Generated by Django 2.0 on 2017-12-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
                name='Paylas',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('baslik', models.CharField(help_text='En fazla 120 karakter olmalı.', max_length=120, unique=True, verbose_name='Başlık')),
                    ('icerik', models.TextField(verbose_name='İçerik')),
                    ('slug', models.CharField(help_text='En fazla 71 karakter olmalı.', max_length=71, verbose_name='Otomatik Link')),
                    ('kayittarihi', models.DateTimeField(auto_now=True, verbose_name='Kayıt Tarihi')),
                ],
                options={
                    'verbose_name': 'Kod',
                    'verbose_name_plural': 'Paylaşımlar',
                },
        ),
    ]
