# Generated by Django 2.0 on 2017-12-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paylas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
                model_name='paylas',
                name='kisaurl',
                field=models.CharField(default='', max_length=20, verbose_name='Kısa URL'),
        ),
    ]
